name: Tests

on: [ 'push', 'pull_request' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3 ]

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phpstan
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader

      - name: Lint composer.json
        run: composer validate

      - name: Tests
        run: ./vendor/bin/pest

      - name: Run PHPStan
        run: phpstan analyse src --level=5
