name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3 ]

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.stability }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, pdo, sqlite, xdebug
          tools: composer:v2, phpstan
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader

      - name: Lint composer.json
        run: composer validate

      - name: Tests
        run: ./vendor/bin/pest

      - name: Run PHPStan
        run: phpstan analyse src --level=5
